apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ template "kubernetes-ingress.defaultTLSSecret.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "kubernetes-ingress.name" . }}
    helm.sh/chart: {{ template "kubernetes-ingress.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
{{ ( include "kubernetes-ingress.gen-certs" . ) | indent 2 }}
