{{/*
Copyright 2020 HAProxy Technologies LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/}}

{{- if and (eq .Values.controller.kind "Deployment") .Values.controller.autoscaling.enabled }}
{{- if not .Values.controller.keda.enabled }}
{{- if or (.Capabilities.APIVersions.Has "autoscaling/v2") (semverCompare ">=1.23.0-0" .Capabilities.KubeVersion.Version) }}
apiVersion: autoscaling/v2
{{- else if .Capabilities.APIVersions.Has "autoscaling/v2beta2" }}
apiVersion: autoscaling/v2beta2
{{- else }}
  {{- fail "ERROR: You must have autoscaling/v2 or autoscaling/v2beta2 to use HorizontalPodAutoscaler" }}
{{- end }}
kind: HorizontalPodAutoscaler
metadata:
{{- if .Values.controller.autoscaling.annotations }}
  annotations:
{{ toYaml .Values.controller.autoscaling.annotations | indent 4 }}
{{- end }}
  name: {{ include "kubernetes-ingress.fullname" . }}
  namespace: {{ include "kubernetes-ingress.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ include "kubernetes-ingress.name" . }}
    helm.sh/chart: {{ include "kubernetes-ingress.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "kubernetes-ingress.fullname" . }}
  minReplicas: {{ .Values.controller.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.controller.autoscaling.maxReplicas }}
  {{- if .Values.controller.autoscaling.behavior }}
  behavior: {{- toYaml .Values.controller.autoscaling.behavior | nindent 4 }}
  {{- end }}
  metrics:
  {{- if .Values.controller.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.controller.autoscaling.targetCPUUtilizationPercentage }}
  {{- end }}
  {{- if .Values.controller.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.controller.autoscaling.targetMemoryUtilizationPercentage }}
  {{- end }}
  {{- if .Values.controller.autoscaling.custom }}
  {{- toYaml .Values.controller.autoscaling.custom | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
