{{- if .Values.gwapijob.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "haproxy-unified-gateway.gwapijob.fullname" . }}
  namespace: {{ include "haproxy-unified-gateway.namespace" . }}
  labels:
    {{- include "haproxy-unified-gateway.gwapijobLabels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "argocd.argoproj.io/hook": PostSync
    {{- with .Values.gwapijob.podAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- with .Values.gwapijob.ttlSecondsAfterFinished }}
  ttlSecondsAfterFinished: {{ . }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "haproxy-unified-gateway.gwapijobLabels" . | nindent 8 }}
      {{- with .Values.gwapijob.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "haproxy-unified-gateway.fullname" . }}-crdjob
      restartPolicy: Never
      {{- with .Values.controller.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: gwapijob
          {{- if .Values.gwapijob.image.repository }}
          image: {{ printf "%s:%s" .Values.gwapijob.image.repository (default .Chart.AppVersion .Values.gwapijob.image.tag) }}
          {{- else }}
          image: {{ include "haproxy-unified-gateway.image" . }}
          {{- end }}
          imagePullPolicy: {{ .Values.controller.image.pullPolicy }}
          command:
            - /usr/local/sbin/hug
            - --job-gwapi={{ .Values.gwapijob.version }}
          {{- with .Values.gwapijob.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.gwapijob.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.gwapijob.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.gwapijob.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  backoffLimit: 0
{{- end }}
